(function(g){var window=this;var XGa=function(a,b){return g.Jb(a,b)},s4=function(a,b,c){a.u.set(b,c)},t4=function(a){s4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.B()).toString(36));
return a},u4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.u,b,c)},YGa=function(a,b){var c=[];
g.lj(b,function(d){try{var e=g.Yn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.On(e)&&c.push(d)},a);
return c},ZGa=function(a,b){var c=YGa(a,b);
g.yb(c,function(d){g.Yn.prototype.remove.call(this,d)},a)},$Ga=function(a){if(a.T){if(a.T.locationOverrideToken)return{locationOverrideToken:a.T.locationOverrideToken};
if(null!=a.T.latitudeE7&&null!=a.T.longitudeE7)return{latitudeE7:a.T.latitudeE7,longitudeE7:a.T.longitudeE7}}return null},aHa=function(a,b){g.db(a,b)||a.push(b)},v4=function(a){var b=0,c;
for(c in a)b++;return b},bHa=function(a,b){var c=b instanceof g.zc?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},w4=function(){},cHa=function(a){try{return g.z.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},dHa=function(a){if(a.qg&&"function"==typeof a.qg)return a.qg();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Gb(a)},eHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.yb(a,b,void 0);else{if(a.uh&&"function"==typeof a.uh)var c=a.uh();else if(a.qg&&"function"==typeof a.qg)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Hb(a);d=dHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},fHa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.l=d);return e},x4=function(a,b){g.Go[a]=!0;
var c=g.Eo();c&&c.publish.apply(c,arguments);g.Go[a]=!1},y4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gHa(this,a.capabilities||""),hHa(this,a.experiments||""))},gHa=function(a,b){a.capabilities.clear();
g.He(b.split(","),g.Pa(XGa,iHa)).forEach(function(c){a.capabilities.add(c)})},hHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},z4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},A4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},jHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},kHa=function(a){return new z4(a)},lHa=function(a){return Array.isArray(a)?g.Jc(a,kHa):[]},B4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},C4=function(a){return Array.isArray(a)?"["+g.Jc(a,B4).join(",")+"]":"null"},D4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},mHa=function(a){return g.Jc(a,function(b){return{key:b.id,
name:b.name}})},E4=function(a,b){return g.$a(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},F4=function(a,b){return g.$a(a,function(c){return A4(c,b)})},nHa=function(){var a=(0,g.Du)();
a&&ZGa(a,a.i.Pj(!0))},G4=function(){var a=g.Gu("yt-remote-connected-devices")||[];
g.vb(a);return a},oHa=function(a){if(g.eb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Jc(a,function(d,e){return 0==e?d:d.substring(c.length)})},pHa=function(a){g.Fu("yt-remote-connected-devices",a,86400)},I4=function(){if(H4)return H4;
var a=g.Gu("yt-remote-device-id");a||(a=D4(),g.Fu("yt-remote-device-id",a,31536E3));for(var b=G4(),c=1,d=a;g.db(b,d);)c++,d=a+"#"+c;return H4=d},J4=function(){var a=G4(),b=I4();
g.db(a,b);g.Iu()&&g.xb(a,b);a=oHa(a);if(g.eb(a))try{g.Vq("remote_sid")}catch(c){}else try{g.Tq("remote_sid",a.join(","),-1)}catch(c){}},qHa=function(){return g.Gu("yt-remote-session-browser-channel")},rHa=function(){return g.Gu("yt-remote-local-screens")||[]},sHa=function(){g.Fu("yt-remote-lounge-token-expiration",!0,86400)},tHa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Jc(rHa(),function(d){return d.loungeToken}),c=g.Jc(a,function(d){return d.loungeToken});
g.uh(c,function(d){return!g.db(b,d)})&&sHa();
g.Fu("yt-remote-local-screens",a,31536E3)},uHa=function(a,b){g.Fu("yt-remote-session-browser-channel",a);
g.Fu("yt-remote-session-screen-id",b);var c=G4(),d=I4();g.db(c,d)||c.push(d);pHa(c);J4()},K4=function(a){a||(g.Hu("yt-remote-session-screen-id"),g.Hu("yt-remote-session-video-id"));
J4();a=G4();g.ib(a,I4());pHa(a)},vHa=function(){if(!L4){var a=g.io();
a&&(L4=new g.Jn(a))}},wHa=function(){vHa();
return L4?!!L4.get("yt-remote-use-staging-server"):!1},xHa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},yHa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},M4=function(a){a.length?zHa(a.shift(),function(){M4(a)}):N4()},AHa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},zHa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.fd(d,g.tg(a));(document.head||document.documentElement).appendChild(d)},N4=function(){var a=yHa();
a&&a(!1,"No cast extension found")},CHa=function(){if(BHa){var a=2,b=yHa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;zHa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",N4,c)}},DHa=function(){CHa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");M4(b)},O4=function(a,b,c){g.C.call(this);
this.G=null!=c?(0,g.A)(a,c):a;this.Gf=b;this.C=(0,g.A)(this.EJ,this);this.i=!1;this.l=0;this.u=this.bb=null;this.B=[]},P4=function(a,b,c){g.C.call(this);
this.B=null!=c?a.bind(c):a;this.Gf=b;this.u=null;this.i=!1;this.l=0;this.bb=null},Q4=function(a){a.bb=g.Lm(function(){a.bb=null;
a.i&&!a.l&&(a.i=!1,Q4(a))},a.Gf);
var b=a.u;a.u=null;a.B.apply(null,b)},R4=function(a){if(g.z.JSON)try{return g.z.JSON.parse(a)}catch(b){}return cHa(a)},S4=function(){},T4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.z.setTimeout(function(){a()},b)},V4=function(a){U4.dispatchEvent(new EHa(U4,a))},EHa=function(a){g.Hl.call(this,"statevent",a)},W4=function(){},FHa=function(){},HHa=function(a){return(a=GHa(a))?new ActiveXObject(a):new XMLHttpRequest},GHa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},X4=function(a,b,c,d){this.i=a;
this.l=b;this.K=c;this.I=d||1;this.C=45E3;this.B=new g.u_(this);this.u=new g.Km;this.u.setInterval(250)},JHa=function(a,b,c){a.Gp=1;
a.Xk=t4(b.clone());a.yn=c;a.G=!0;IHa(a,null)},Y4=function(a,b,c,d,e){a.Gp=1;
a.Xk=t4(b.clone());a.yn=null;a.G=c;e&&(a.FG=!1);IHa(a,d)},IHa=function(a,b){a.wp=g.B();
Z4(a);a.Rl=a.Xk.clone();u4(a.Rl,"t",a.I);a.Fs=0;a.ye=a.i.xx(a.i.ds()?b:null);0<a.tw&&(a.Qu=new P4((0,g.A)(a.CH,a,a.ye),a.tw));a.B.va(a.ye,"readystatechange",a.fQ);var c=a.mm?g.Qb(a.mm):{};a.yn?(a.Dv="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.ye.send(a.Rl,a.Dv,a.yn,c)):(a.Dv="GET",a.FG&&!g.xe&&(c.Connection="close"),a.ye.send(a.Rl,a.Dv,null,c));a.i.ii(1)},MHa=function(a,b,c){for(var d=!0;!a.Jm&&a.Fs<c.length;){var e=KHa(a,c);
if(e==$4){4==b&&(a.Rk=4,V4(15),d=!1);break}else if(e==LHa){a.Rk=4;V4(16);d=!1;break}else a5(a,e)}4==b&&0==c.length&&(a.Rk=1,V4(17),d=!1);a.zi=a.zi&&d;d||(b5(a),c5(a))},KHa=function(a,b){var c=a.Fs,d=b.indexOf("\n",c);
if(-1==d)return $4;c=Number(b.substring(c,d));if(isNaN(c))return LHa;d+=1;if(d+c>b.length)return $4;var e=b.substr(d,c);a.Fs=d+c;return e},OHa=function(a,b){a.wp=g.B();
Z4(a);var c=b?window.location.hostname:"";a.Rl=a.Xk.clone();s4(a.Rl,"DOMAIN",c);s4(a.Rl,"t",a.I);try{a.Di=new ActiveXObject("htmlfile")}catch(n){b5(a);a.Rk=7;V4(22);c5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in d5)h=d5[h];else if(h in NHa)h=d5[h]=NHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
d5[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.cd(g.bc("b/12014412"),d+"</body></html>");a.Di.open();a.Di.write(g.Zc(c));a.Di.close();a.Di.parentWindow.m=(0,g.A)(a.xP,a);a.Di.parentWindow.d=(0,g.A)(a.QF,a,!0);a.Di.parentWindow.rpcClose=(0,g.A)(a.QF,a,!1);c=a.Di.createElement("DIV");a.Di.parentWindow.document.body.appendChild(c);d=g.Ec(a.Rl.toString());d=g.kd(g.Ac(d));d=g.cd(g.bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.dd(c,d);a.i.ii(1)},Z4=function(a){a.BA=g.B()+a.C;
PHa(a,a.C)},PHa=function(a,b){if(null!=a.Lp)throw Error("WatchDog timer not null");
a.Lp=T4((0,g.A)(a.FP,a),b)},e5=function(a){a.Lp&&(g.z.clearTimeout(a.Lp),a.Lp=null)},c5=function(a){a.i.BB()||a.Jm||a.i.Us(a)},b5=function(a){e5(a);
g.Yf(a.Qu);a.Qu=null;a.u.stop();g.tBa(a.B);if(a.ye){var b=a.ye;a.ye=null;b.abort();b.dispose()}a.Di&&(a.Di=null)},a5=function(a,b){try{a.i.HF(a,b),a.i.ii(4)}catch(c){}},RHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;QHa(a,b,function(h){h?c(!0):g.z.setTimeout(function(){RHa(a,b,c,d,f)},f)})}},QHa=function(a,b,c){var d=new Image;
d.onload=function(){try{f5(d),c(!0)}catch(e){}};
d.onerror=function(){try{f5(d),c(!1)}catch(e){}};
d.onabort=function(){try{f5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{f5(d),c(!1)}catch(e){}};
g.z.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
bHa(d,a)},f5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},g5=function(a){g.am.call(this);
this.headers=new g.Nm;this.ba=a||null;this.B=!1;this.Z=this.i=null;this.wa=this.T="";this.G=0;this.u="";this.C=this.ha=this.K=this.da=!1;this.I=0;this.U=null;this.Aa="";this.V=this.fa=!1},SHa=function(a){return g.ve&&g.Xd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},THa=function(a){return"content-type"==a.toLowerCase()},VHa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;UHa(a);h5(a)},UHa=function(a){a.da||(a.da=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},XHa=function(a){if(a.B&&"undefined"!=typeof g.x_)if(a.Z[1]&&4==i5(a)&&2==a.getStatus())j5(a,"Local request error detected and ignored");
else if(a.K&&4==i5(a))g.Lm(a.EF,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){j5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.td(1,String(a.T));if(!f&&g.z.self&&g.z.self.location){var h=g.z.self.location.protocol;f=h.substr(0,h.length-1)}e=!WHa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<i5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";UHa(a)}}finally{h5(a)}}},h5=function(a,b){if(a.i){YHa(a);
var c=a.i,d=a.Z[0]?g.Ia:null;a.i=null;a.Z=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},YHa=function(a){a.i&&a.V&&(a.i.ontimeout=null);
a.U&&(g.z.clearTimeout(a.U),a.U=null)},i5=function(a){return a.i?a.i.readyState:0},k5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},j5=function(a,b){return b+" ["+a.wa+" "+a.T+" "+a.getStatus()+"]"},ZHa=function(a){this.i=a;
this.l=new S4},$Ha=function(a){var b=l5(a.i,a.lq,"/mail/images/cleardot.gif");
t4(b);RHa(b.toString(),5E3,(0,g.A)(a.wK,a),3,2E3);a.ii(1)},n5=function(a){var b=a.i.K;
if(null!=b)V4(5),b?(V4(11),m5(a.i,a,!1)):(V4(12),m5(a.i,a,!0));else if(a.Bg=new X4(a,void 0,void 0,void 0),a.Bg.mm=a.uw,b=a.i,b=l5(b,b.ds()?a.bq:null,a.ww),V4(5),!g.ve||g.Yd(10))u4(b,"TYPE","xmlhttp"),Y4(a.Bg,b,!1,a.bq,!1);else{u4(b,"TYPE","html");var c=a.Bg;a=!!a.bq;c.Gp=3;c.Xk=t4(b.clone());OHa(c,a)}},o5=function(a,b,c){this.Ja=1;
this.i=[];this.u=[];this.B=new S4;this.I=a||null;this.K=null!=b?b:null;this.C=c||!1},aIa=function(a,b){this.i=a;
this.map=b;this.context=null},bIa=function(a,b,c,d){g.Hl.call(this,"timingevent",a);
this.size=b;this.Tr=d},cIa=function(a){g.Hl.call(this,"serverreachability",a)},fIa=function(a){dIa(a);
if(3==a.Ja){var b=a.yr++,c=a.At.clone();s4(c,"SID",a.l);s4(c,"RID",b);s4(c,"TYPE","terminate");p5(a,c);b=new X4(a,a.l,b,void 0);b.Gp=2;b.Xk=t4(c.clone());bHa(new Image,b.Xk.toString());b.wp=g.B();Z4(b)}eIa(a)},gIa=function(a){a.SK(1,0);
a.At=l5(a,null,a.xw);q5(a)},dIa=function(a){a.bl&&(a.bl.abort(),a.bl=null);
a.Wd&&(a.Wd.cancel(),a.Wd=null);a.Qj&&(g.z.clearTimeout(a.Qj),a.Qj=null);r5(a);a.ng&&(a.ng.cancel(),a.ng=null);a.ol&&(g.z.clearTimeout(a.ol),a.ol=null)},hIa=function(a,b){if(0==a.Ja)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new aIa(a.uM++,b));2!=a.Ja&&3!=a.Ja||q5(a)},iIa=function(a){var b=0;
a.Wd&&b++;a.ng&&b++;return b},q5=function(a){a.ng||a.ol||(a.ol=T4((0,g.A)(a.OF,a),0),a.Bo=0)},kIa=function(a,b){if(1==a.Ja){if(!b){a.yr=Math.floor(1E5*Math.random());
var c=a.yr++,d=new X4(a,"",c,void 0);d.mm=a.Ki;var e=s5(a),f=a.At.clone();s4(f,"RID",c);s4(f,"CVER","1");p5(a,f);JHa(d,f,e);a.ng=d;a.Ja=2}}else 3==a.Ja&&(b?jIa(a,b):0==a.i.length||a.ng||jIa(a))},jIa=function(a,b){if(b)if(6<a.Km){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.yr-1;var d=s5(a)}else c=b.K,d=b.yn;else c=a.yr++,d=s5(a);var e=a.At.clone();s4(e,"SID",a.l);s4(e,"RID",c);s4(e,"AID",a.Vo);p5(a,e);c=new X4(a,a.l,c,a.Bo+1);c.mm=a.Ki;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ng=c;JHa(c,e,d)},p5=function(a,b){if(a.wf){var c=a.wf.pD();
c&&g.Ab(c,function(d,e){s4(b,e,d)})}},s5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Km&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Qn:e.Qn},f++){e.Qn=a.i[f].i;var h=a.i[f].map;e.Qn=6>=a.Km?f:e.Qn-d;try{g.Ab(h,function(l){return function(m,n){c.push("req"+l.Qn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Qn+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},lIa=function(a){a.Wd||a.Qj||(a.G=1,a.Qj=T4((0,g.A)(a.NF,a),0),a.ko=0)},t5=function(a){if(a.Wd||a.Qj||3<=a.ko)return!1;
a.G++;a.Qj=T4((0,g.A)(a.NF,a),mIa(a,a.ko));a.ko++;return!0},m5=function(a,b,c){a.Bv=c;
a.Li=b.Nj;a.C||gIa(a)},r5=function(a){null!=a.Rm&&(g.z.clearTimeout(a.Rm),a.Rm=null)},mIa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},u5=function(a,b){if(2==b||9==b){var c=null;
a.wf&&(c=null);var d=(0,g.A)(a.NQ,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),t4(c));QHa(c.toString(),1E4,d)}else V4(2);nIa(a,b)},nIa=function(a,b){a.Ja=0;
a.wf&&a.wf.EC(b);eIa(a);dIa(a)},eIa=function(a){a.Ja=0;
a.Li=-1;if(a.wf)if(0==a.u.length&&0==a.i.length)a.wf.gx();else{g.lb(a.u);var b=g.lb(a.i);a.u.length=0;a.i.length=0;a.wf.gx(b)}},l5=function(a,b,c){var d=g.Ym(c);
if(""!=d.i)b&&g.Sm(d,b+"."+d.i),g.Tm(d,d.B);else{var e=window.location;d=fHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Fq&&g.Ab(a.Fq,function(f,h){s4(d,h,f)});
s4(d,"VER",a.Km);p5(a,d);return d},oIa=function(){},pIa=function(){this.i=[];
this.l=[]},qIa=function(a,b){this.action=a;
this.params=b||{}},v5=function(a,b){g.C.call(this);
this.i=new g.I(this.pP,0,this);g.D(this,this.i);this.Gf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.A)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},w5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.Z=a;this.G=b;this.u=new g.In;this.l=new v5(this.qQ,this);this.i=null;this.U=!1;this.C=null;this.T="";this.K=this.B=0;this.I=[];this.ba=c;this.V=d;this.fa=e},rIa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Bv,sessionId:a.i.l,arrayId:a.i.Vo}},sIa=function(a,b){a.K=b||0;
a.l.stop();x5(a);a.i&&(3==a.i.getState()&&kIa(a.i),fIa(a.i));a.K=0},y5=function(a){return!!a.i&&3==a.i.getState()},x5=function(a){if(a.i){var b=a.V(),c=a.i.Ki||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Ki=c}},z5=function(a){this.scheme="https";
this.port=this.domain="";this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.td(4,a))||"";b&&(this.port=":"+b);this.domain=g.ud(a)||"";a=g.Pc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.xc(a,"10.0")&&(this.l=!1))},A5=function(a,b){var c=a.i;
a.l&&(c=a.scheme+"://"+a.domain+a.port+a.i);return g.Id(c+b,{})},B5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.$p(b,a)},wIa=function(){var a=tIa;
uIa();C5.push(a);vIa()},D5=function(a,b){uIa();
var c=xIa(a,String(b));g.eb(C5)?yIa(c):(vIa(),g.yb(C5,function(d){d(c)}))},E5=function(a){D5("CP",a)},uIa=function(){C5||(C5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",C5,void 0))},yIa=function(a){var b=(F5+1)%50;
F5=b;G5[b]=a;H5||(H5=49==b)},vIa=function(){var a=C5;
if(G5[0]){var b=H5?F5:-1;do{b=(b+1)%50;var c=G5[b];g.yb(a,function(d){d(c)})}while(b!=F5);
G5=Array(50);F5=-1;H5=!1}},xIa=function(a,b){var c=(g.B()-zIa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},I5=function(a){g.O.call(this);
this.G=a;this.screens=[]},AIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},BIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.He(a.screens,function(f){return!!E4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=AIa(a,b[d])||c;return c},CIa=function(a,b){var c=a.screens.length;
a.screens=g.He(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},J5=function(a,b,c,d){g.O.call(this);
this.u=a;this.G=b;this.B=c;this.C=d;this.l=0;this.i=null;this.bb=NaN},L5=function(a){I5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;K5(this);this.info("Initializing with "+C4(this.screens))},DIa=function(a){if(a.screens.length){var b=g.Jc(a.screens,function(d){return d.id}),c=A5(a.l,"/pairing/get_lounge_token_batch");
B5(a.l,c,{screen_ids:b.join(",")},(0,g.A)(a.tL,a),(0,g.A)(a.sL,a))}},K5=function(a){if(g.Ro("deprecate_pair_servlet_enabled"))return BIa(a,[]);
var b=lHa(rHa());b=g.He(b,function(c){return!c.uuid});
return BIa(a,b)},M5=function(a,b){tHa(g.Jc(a.screens,jHa));
b&&sHa()},O5=function(a,b){g.O.call(this);
this.G=b;var c=g.Gu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.G(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.db(c,l)}this.i=d;this.C=a;this.u=this.B=NaN;this.l=null;N5("Initialized with "+g.Pj(this.i))},P5=function(a,b,c){var d=A5(a.C,"/pairing/get_screen_availability");
B5(a.C,d,{lounge_token:b.token},(0,g.A)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},Q5=function(a,b){a:if(v4(b)!=v4(a.i))var c=!1;
else{c=g.Hb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(N5("Updated online screens: "+g.Pj(a.i)),a.i=b,a.S("screenChange"));EIa(a)},R5=function(a){isNaN(a.u)||g.Do(a.u);
a.u=g.Bo((0,g.A)(a.Cz,a),0<a.B&&a.B<g.B()?2E4:1E4)},N5=function(a){D5("OnlineScreenService",a)},FIa=function(a){var b={};
g.yb(a.G(),function(c){c.token?b[c.token]=c.id:this.Cd("Requesting availability of screen w/o lounge token.")});
return b},EIa=function(a){a=g.Hb(g.Bb(a.i,function(b){return b}));
g.vb(a);a.length?g.Fu("yt-remote-online-screen-ids",a.join(","),60):g.Hu("yt-remote-online-screen-ids")},S5=function(a){I5.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.u=[];this.C={};GIa(this)},IIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Pg();if(h=(c?F4(h,c):null)||F4(h,b)){h.uuid=b;var l=T5(a,h);P5(a.i,l,function(m){e(m?l:null)})}else c?HIa(a,c,(0,g.A)(function(m){var n=T5(this,new z4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));P5(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},JIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},KIa=function(a,b,c){P5(a.i,b,c)},HIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.$p(A5(a.B,"/pairing/get_lounge_token_batch"),e)},LIa=function(a){a.screens=a.l.Pg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+C4(a.screens))},GIa=function(a){U5(a);
a.l=new L5(a.B);a.l.subscribe("screenChange",(0,g.A)(a.zL,a));LIa(a);a.u=lHa(g.Gu("yt-remote-automatic-screen-cache")||[]);U5(a);a.info("Initializing automatic screens: "+C4(a.u));a.i=new O5(a.B,(0,g.A)(a.Pg,a,!0));a.i.subscribe("screenChange",(0,g.A)(function(){this.S("onlineScreenChange")},a))},T5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=F4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),MIa(a));U5(a);a.C[b.uuid]=b.id;g.Fu("yt-remote-device-id-map",a.C,31536E3);return b},MIa=function(a){a=g.He(a.u,function(b){return"shortLived"!=b.idType});
g.Fu("yt-remote-automatic-screen-cache",g.Jc(a,jHa))},U5=function(a){a.C=g.Gu("yt-remote-device-id-map")||{}},V5=function(a,b,c){g.O.call(this);
this.fa=c;this.B=a;this.i=b;this.u=null},W5=function(a,b){a.u=b;
a.S("sessionScreen",a.u)},X5=function(a,b){D5(a.fa,b)},Y5=function(a,b,c){V5.call(this,a,b,"CastSession");
var d=this;this.da=c;this.l=null;this.V=(0,g.A)(this.JJ,this);this.Z=(0,g.A)(this.MP,this);this.U=g.Bo(function(){NIa(d,null)},12E4);
this.I=this.C=this.G=this.K=0;this.ba=!1;this.T="unknown"},Z5=function(a,b){g.Do(a.I);
a.I=0;0==b?OIa(a):a.I=g.Bo(function(){OIa(a)},b)},OIa=function(a){PIa(a,"getLoungeToken");
g.Do(a.C);a.C=g.Bo(function(){QIa(a,null)},3E4)},PIa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Pj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.A)(function(){X5(this,"Failed to send message: "+b+".")},a)):X5(a,"Sending yt message without session: "+g.Pj(c))},$5=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.GD(b,function(c){W5(a,c)},function(){return a.Zf()},5)):a.Zf(Error("Waiting for session status timed out."))},SIa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new z4(b);RIa(a,d,function(e){e?(a.ba=!0,T5(a.B,d),W5(a,d),a.T="unknown",Z5(a,c)):(g.yo(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Zf())},5)},NIa=function(a,b){g.Do(a.U);
a.U=0;b?a.da.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?SIa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.yo(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),$5(a,b.screenId))):(g.yo(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
$5(a,b.screenId)):$5(a,b.screenId):a.Zf(Error("Waiting for session status timed out."))},QIa=function(a,b){g.Do(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.T=c,Z5(a,3E4)):(a.u&&(a.u.token=b.loungeToken,T5(a.B,a.u)),a.S("sessionScreen",a.u),a.ba=!1,a.T="unknown",Z5(a,b.loungeTokenRefreshIntervalMs))},RIa=function(a,b,c,d){g.Do(a.G);
a.G=0;KIa(a.B,b,function(e){e||0>d?c(e):a.G=g.Bo(function(){RIa(a,b,c,d-1)},300)})},TIa=function(a){g.Do(a.K);
a.K=0;g.Do(a.G);a.G=0;g.Do(a.U);a.U=0;g.Do(a.C);a.C=0;g.Do(a.I);a.I=0},a6=function(a,b,c){V5.call(this,a,b,"DialSession");
this.C=this.K=null;this.T="";this.Z=c;this.V=null;this.I=g.Ia;this.G=NaN;this.U=(0,g.A)(this.KJ,this);this.l=g.Ia},UIa=function(a){a.l=a.B.FB(a.T,a.i.label,a.i.friendlyName,(0,g.A)(function(b){this.l=g.Ia;
W5(this,b)},a),(0,g.A)(function(b){this.l=g.Ia;
this.Zf(b)},a))},VIa=function(a){var b={};
b.pairingCode=a.T;b.theme=a.Z;wHa()&&(b.env_useStageMdx=1);return g.Gd(b)},b6=function(a,b){V5.call(this,a,b,"ManualSession");
this.l=g.Bo((0,g.A)(this.Wo,this,null),150)},c6=function(a,b){g.O.call(this);
this.B=b;this.l=a;this.K=b.appId||"233637DE";this.C=b.theme||"cl";this.T=b.disableCastApi||!1;this.i=null;this.I=!1;this.u=[];this.G=(0,g.A)(this.FO,this)},WIa=function(a,b){return b?g.$a(a.u,function(c){return A4(b,c.label)},a):null},d6=function(a){D5("Controller",a)},tIa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},e6=function(a){return a.I||!!a.u.length||!!a.i},f6=function(a,b,c){b!=a.i&&(g.Yf(a.i),(a.i=b)?(c?a.S("yt-remote-cast2-receiver-resumed",
b.i):a.S("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.A)(a.LF,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Wo(null)):a.S("yt-remote-cast2-session-change",null))},XIa=function(a){var b=a.l.EB(),c=a.i&&a.i.i;
a=g.Jc(b,function(d){c&&A4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=WIa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},cJa=function(a,b,c,d){d.disableCastApi?g6("Cannot initialize because disabled by Mdx config."):YIa()?ZIa(b,d)&&(h6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?$Ia(a,c):(window.__onGCastApiAvailable=function(e,f){e?$Ia(a,c):(i6("Failed to load cast API: "+f),j6(!1),h6(!1),g.Hu("yt-remote-cast-available"),g.Hu("yt-remote-cast-receiver"),
aJa(),c(!1))},d.loadCastApiSetupScript?g.No("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?DHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?N4():(CHa(),M4(bJa.map(AHa))))):g6("Cannot initialize because not running Chrome")},aJa=function(){g6("dispose");
var a=k6();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);dJa(!1);g.Jo(l6);l6.length=0},m6=function(){return!!g.Gu("yt-remote-cast-installed")},eJa=function(){var a=g.Gu("yt-remote-cast-receiver");
return a?a.friendlyName:null},fJa=function(){g6("clearCurrentReceiver");
g.Hu("yt-remote-cast-receiver")},gJa=function(){return m6()?k6()?k6().getCastSession():(i6("getCastSelector: Cast is not initialized."),null):(i6("getCastSelector: Cast API is not installed!"),null)},o6=function(){m6()?k6()?n6()?(g6("Requesting cast selector."),k6().requestSession()):(g6("Wait for cast API to be ready to request the session."),l6.push(g.Io("yt-remote-cast2-api-ready",o6))):i6("requestCastSelector: Cast is not initialized."):i6("requestCastSelector: Cast API is not installed!")},p6=
function(a,b){n6()?k6().setConnectedScreenStatus(a,b):i6("setConnectedScreenStatus called before ready.")},YIa=function(){var a=0<=g.Pc.search(/ (CrMo|Chrome|CriOS)\//);
return g.DA||a},hJa=function(a,b){k6().init(a,b)},ZIa=function(a,b){var c=!1;
k6()||(c=new c6(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.Fu("yt-remote-cast-available",d);x4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){g6("onReceiverSelected: "+d.friendlyName);
g.Fu("yt-remote-cast-receiver",d);x4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){g6("onReceiverResumed: "+d.friendlyName);
g.Fu("yt-remote-cast-receiver",d);x4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){g6("onSessionChange: "+B4(d));
d||g.Hu("yt-remote-cast-receiver");x4("yt-remote-cast2-session-change",d)}),g.Da("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
g6("cloudview.createSingleton_: "+c);return c},k6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},$Ia=function(a,b){j6(!0);
h6(!1);hJa(a,function(c){c?(dJa(!0),g.Ko("yt-remote-cast2-api-ready")):(i6("Failed to initialize cast API."),j6(!1),g.Hu("yt-remote-cast-available"),g.Hu("yt-remote-cast-receiver"),aJa());b(c)})},g6=function(a){D5("cloudview",a)},i6=function(a){D5("cloudview",a)},j6=function(a){g6("setCastInstalled_ "+a);
g.Fu("yt-remote-cast-installed",a)},n6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},dJa=function(a){g6("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},h6=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},q6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.i=null;this.hasNext=this.hj=!1;this.T=this.G=this.l=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},r6=function(a){a.audioTrackId=null;
a.i=null;a.playerState=-1;a.hj=!1;a.hasNext=!1;a.K=0;a.I=g.B();a.C=0;a.l=0;a.G=0;a.T=0;a.B=NaN;a.u=!1},s6=function(a){return a.Ib()?(g.B()-a.I)/1E3:0},t6=function(a,b){a.K=b;
a.I=g.B()},u6=function(a){switch(a.playerState){case 1:case 1081:return(g.B()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},v6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&r6(a)},w6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Rb(a.i);b.hasPrevious=a.hj;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.l;b.duration=a.G;b.loadedTime=a.T;b.liveIngestionTime=a.B;return b},y6=function(a,b){g.O.call(this);
this.Ja=0;this.u=a;this.C=[];this.B=new pIa;this.l=this.i=null;this.K=(0,g.A)(this.hN,this);this.G=(0,g.A)(this.Ar,this);this.I=(0,g.A)(this.gN,this);this.T=(0,g.A)(this.oN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Rz,this),iJa(this))):c=3;0!=c&&(b?this.Rz(c):g.Bo((0,g.A)(function(){this.Rz(c)},this),0));
var d=gJa();d&&x6(this,d);this.subscribe("yt-remote-cast2-session-change",this.T)},z6=function(a){return new q6(a.u.getPlayerContextData())},iJa=function(a){g.yb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.CO,b),this))},a)},jJa=function(a){g.yb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},A6=function(a){return 1==a.getState()},B6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},D6=function(a,b,c){var d=z6(a);
t6(d,c);-1E3!=d.playerState&&(d.playerState=b);C6(a,d)},E6=function(a,b,c){a.u.sendMessage(b,c)},C6=function(a,b){jJa(a);
a.u.setPlayerContextData(w6(b));iJa(a)},x6=function(a,b){a.l&&(a.l.removeUpdateListener(a.K),a.l.removeMediaListener(a.G),a.Ar(null));
a.l=b;a.l&&(E5("Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.K),a.l.addMediaListener(a.G),a.l.media.length&&a.Ar(a.l.media[0]))},kJa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=z6(a);b.contentId!=d.videoId&&E5("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;t6(d,a.i.getEstimatedTime());C6(a,d)}else E5("No cast media video. Ignoring state update.")},F6=function(a,b,c){return(0,g.A)(function(d){this.Cd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Cd("Retrying "+b+" using MDx browser channel."),E6(this,b,c))},a)},G6=function(a,b,c){g.O.call(this);
this.C=NaN;this.Z=!1;this.K=this.I=this.U=this.V=NaN;this.T=[];this.B=this.G=this.u=this.Cb=this.i=null;this.fa=a;this.T.push(g.cp(window,"beforeunload",(0,g.A)(this.nL,this)));this.l=[];this.Cb=new q6;this.da=b.id;this.ba=b.idType;this.i=lJa(this,c);this.i.subscribe("handlerOpened",this.lN,this);this.i.subscribe("handlerClosed",this.iN,this);this.i.subscribe("handlerError",this.jN,this);this.i.subscribe("handlerMessage",this.kN,this);this.i.av(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Cb.videoId;g.Iu()&&g.Fu("yt-remote-session-video-id",d)},this)},H6=function(a){D5("conn",a)},lJa=function(a,b){return new w5(A5(a.fa,"/bc"),b,!1,function(){return a.JB()},"shortLived"==a.ba)},I6=function(a,b){a.S("proxyStateChange",b)},mJa=function(a){a.C=g.Bo((0,g.A)(function(){H6("Connecting timeout");
this.xo(1)},a),2E4)},J6=function(a){g.Do(a.C);
a.C=NaN},K6=function(a){g.Do(a.V);
a.V=NaN},nJa=function(a){L6(a);
a.U=g.Bo((0,g.A)(function(){M6(this,"getNowPlaying")},a),2E4)},L6=function(a){g.Do(a.U);
a.U=NaN},pJa=function(a,b){b&&(J6(a),K6(a));
var c=y5(a.i)&&isNaN(a.C);b==c?b&&(I6(a,1),M6(a,"getSubtitlesTrack")):b?(a.FD()&&a.Cb.reset(),I6(a,1),M6(a,"getNowPlaying"),oJa(a)):a.xo(1)},qJa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Cb.videoId&&(g.Mb(b.params)?a.Cb.i=null:a.Cb.i=b.params,a.S("remotePlayerChange"))},rJa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Cb.listId=b.params.listId||a.Cb.listId;v6(a.Cb,c,d);a.S("remoteQueueChange")},tJa=function(a,b){b.params=b.params||{};
rJa(a,b);sJa(a,b);a.S("autoplayDismissed")},sJa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
t6(a.Cb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Cb.playerState&&(c=-1E3);a.Cb.playerState=c;c=Number(b.params.loadedTime);a.Cb.T=isNaN(c)?0:c;c=Number(b.params.duration);a.Cb.G=isNaN(c)?0:c;c=a.Cb;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.Cb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.Cb.playerState?nJa(a):L6(a);a.S("remotePlayerChange")},uJa=function(a,b){if(-1E3!=
a.Cb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Cb.playerState=c;c=parseInt(b.params.currentTime,10);t6(a.Cb,isNaN(c)?0:c);a.S("remotePlayerChange")}},vJa=function(a,b){var c="true"==b.params.muted;
a.Cb.volume=parseInt(b.params.volume,10);a.Cb.muted=c;a.S("remotePlayerChange")},wJa=function(a,b){a.G=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},xJa=function(a,b){var c="true"==b.params.hasNext;
a.Cb.hj="true"==b.params.hasPrevious;a.Cb.hasNext=c;a.S("previousNextChange")},oJa=function(a){g.Do(a.K);
a.K=g.Bo((0,g.A)(a.xo,a,1),864E5)},M6=function(a,b,c){c?H6("Sending: action="+b+", params="+g.Pj(c)):H6("Sending: action="+b);
a.i.sendMessage(b,c)},N6=function(a){I5.call(this,"ScreenServiceProxy");
this.Ff=a;this.i=[];this.i.push(this.Ff.$_s("screenChange",(0,g.A)(this.OJ,this)));this.i.push(this.Ff.$_s("onlineScreenChange",(0,g.A)(this.jO,this)))},BJa=function(a,b){vHa();
if(!L4||!L4.get("yt-remote-disable-remote-module-for-dev")){b=g.M("MDX_CONFIG")||b;nHa();J4();O6||(O6=new z5(b?b.loungeApiHost:void 0),wHa()&&(O6.i="/api/loungedev"));P6||(P6=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",P6,void 0));yJa();var c=Q6();if(!c){var d=new S5(O6);g.Da("yt.mdx.remote.screenService_",d,void 0);c=Q6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});cJa(a,d,function(h){h?R6()&&p6(R6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){x4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ha("yt.mdx.remote.initialized_")){g.Da("yt.mdx.remote.initialized_",!0,void 0);
S6("Initializing: "+g.Pj(b));T6.push(g.Io("yt-remote-cast2-availability-change",function(){x4("yt-remote-receiver-availability-change")}));
T6.push(g.Io("yt-remote-cast2-receiver-selected",function(){U6(null);x4("yt-remote-auto-connect","cast-selector-receiver")}));
T6.push(g.Io("yt-remote-cast2-receiver-resumed",function(){x4("yt-remote-receiver-resumed","cast-selector-receiver")}));
T6.push(g.Io("yt-remote-cast2-session-change",zJa));T6.push(g.Io("yt-remote-connection-change",function(h){h?p6(R6(),"YouTube TV"):V6()||(p6(null,null),fJa())}));
e=W6();b.isAuto&&(e.id+="#dial");g.Ro("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);S6(" -- with channel params: "+g.Pj(e));e?(g.Fu("yt-remote-session-app",e.app),g.Fu("yt-remote-session-name",e.name)):(g.Hu("yt-remote-session-app"),g.Hu("yt-remote-session-name"));g.Da("yt.mdx.remote.channelParams_",e,void 0);c.start();R6()||AJa()}}},CJa=function(){var a=Q6().Ff.$_gos();
var b=X6();b&&Y6()&&(E4(a,b)||a.push(b));return mHa(a)},Z6=function(){var a=DJa();
!a&&m6()&&eJa()&&(a={key:"cast-selector-receiver",name:eJa()});return a},DJa=function(){var a=CJa(),b=X6();
b||(b=V6());return g.$a(a,function(c){return b&&A4(b,c.key)?!0:!1})},X6=function(){var a=R6();
if(!a)return null;var b=Q6().Pg();return F4(b,a)},zJa=function(a){S6("remote.onCastSessionChange_: "+B4(a));
if(a){var b=X6();if(b&&b.id==a.id){if(p6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))$6&&($6.token=a),(b=Y6())&&b.av(a)}else b&&a7(),b7(a,1)}else Y6()&&a7()},a7=function(){n6()?k6().stopSession():i6("stopSession called before API ready.");
var a=Y6();a&&(a.disconnect(1),c7(null))},d7=function(){var a=Y6();
return!!a&&3!=a.getProxyState()},S6=function(a){D5("remote",a)},Q6=function(){if(!e7){var a=g.Ha("yt.mdx.remote.screenService_");
e7=a?new N6(a):null}return e7},R6=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},EJa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},FJa=function(){return g.Ha("yt.mdx.remote.connectData_")},U6=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},Y6=function(){return g.Ha("yt.mdx.remote.connection_")},c7=function(a){var b=Y6();
U6(null);a||EJa("");g.Da("yt.mdx.remote.connection_",a,void 0);P6&&(g.yb(P6,function(c){c(a)}),P6.length=0);
b&&!a?x4("yt-remote-connection-change",!1):!b&&a&&x4("yt-remote-connection-change",!0)},V6=function(){var a=g.Iu();
if(!a)return null;var b=Q6();if(!b)return null;b=b.Pg();return F4(b,a)},b7=function(a,b){R6();
X6()&&X6();if(f7)$6=a;else{EJa(a.id);var c=new G6(O6,a,W6());c.connect(b,FJa());c.subscribe("beforeDisconnect",function(d){x4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){Y6()&&(Y6(),c7(null))});
c.subscribe("browserChannelAuthError",function(){var d=X6();d&&"shortLived"==d.idType&&(n6()?k6().handleBrowserChannelAuthError():i6("refreshLoungeToken called before API ready."))});
c7(c)}},AJa=function(){var a=V6();
a?(S6("Resume connection to: "+B4(a)),b7(a,0)):(K4(),fJa(),S6("Skipping connecting because no session screen found."))},yJa=function(){var a=W6();
if(g.Mb(a)){a=I4();var b=g.Gu("yt-remote-session-name")||"",c=g.Gu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},W6=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},g7=function(a,b,c){g.C.call(this);
var d=this;this.l=a;this.F=b;this.tb=c;this.events=new g.cO(this);this.U=this.events.L(this.F,"onVolumeChange",function(e){GJa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.aL(64);this.i=new g.I(this.PG,500,this);this.u=new g.I(this.QG,1E3,this);this.K=new O4(this.dR,0,this);this.B={};this.T=new g.I(this.sH,1E3,this);this.I=new P4(this.seekTo,1E3,this);this.V=g.Ia;g.D(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.SN);this.events.L(b,"captionschanged",this.eN);this.events.L(b,"captionssettingschanged",this.VG);this.events.L(b,"videoplayerreset",this.Ju);this.events.L(b,"mdxautoplaycancel",function(){d.tb.YC()});
a=this.tb;a.ka();a.subscribe("proxyStateChange",this.GF,this);a.subscribe("remotePlayerChange",this.Gr,this);a.subscribe("remoteQueueChange",this.Ju,this);a.subscribe("previousNextChange",this.DF,this);a.subscribe("nowAutoplaying",this.yF,this);a.subscribe("autoplayDismissed",this.YE,this);g.D(this,this.i);g.D(this,this.u);g.D(this,this.K);g.D(this,this.T);g.D(this,this.I);this.VG();this.Ju();this.Gr()},GJa=function(a,b){if(h7(a)){a.tb.unsubscribe("remotePlayerChange",a.Gr,a);
var c=Math.round(b.volume),d=!!b.muted,e=z6(a.tb);if(c!==e.volume||d!==e.muted)a.tb.setVolume(c,d),a.T.start();a.tb.subscribe("remotePlayerChange",a.Gr,a)}},HJa=function(a){a.xb(0);
a.i.stop();a.qb(new g.aL(64))},i7=function(a,b){if(h7(a)&&!a.C){var c=null;
b&&(c={style:a.F.getSubtitlesUserSettings()},g.Tb(c,b));a.tb.IB(a.F.getVideoData(1).videoId,c);a.B=z6(a.tb).i}},j7=function(a,b){var c=a.F.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.F.getVideoData(1);a.tb.playVideo(c.videoId,b,d,e,c.playerParams,c.fa,$Ga(c));a.qb(new g.aL(1))},IJa=function(a,b){if(b){var c=a.F.getOption("captions","tracklist",{aE:1});
c&&c.length?(a.F.setOption("captions","track",b),a.C=!1):(a.F.loadModule("captions"),a.C=!0)}else a.F.setOption("captions","track",{})},h7=function(a){return z6(a.tb).videoId===a.F.getVideoData(1).videoId},k7=function(){g.V.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",R:{role:"dialog"},N:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",N:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",Y:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",N:[{D:"button",ga:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Y:"Learn more"},{D:"button",ga:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],Y:"OK"}]}]}]});this.i=new g.JM(this,250);this.learnMoreButton=
this.ea("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ea("ytp-mdx-manual-pairing-popup-ok");g.D(this,this.i);this.L(this.learnMoreButton,"click",this.l);this.L(this.okButton,"click",this.u)},l7=function(){g.V.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",R:{role:"dialog"},N:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",N:[{D:"div",J:"ytp-mdx-popup-title",Y:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",Y:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",N:[{D:"button",ga:["ytp-button","ytp-mdx-privacy-popup-cancel"],Y:"Cancel"},{D:"button",ga:["ytp-button","ytp-mdx-privacy-popup-confirm"],
Y:"Confirm"}]}]}]});this.i=new g.JM(this,250);this.cancelButton=this.ea("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ea("ytp-mdx-privacy-popup-confirm");g.D(this,this.i);this.L(this.cancelButton,"click",this.l);this.L(this.confirmButton,"click",this.u)},m7=function(a){g.V.call(this,{D:"div",
J:"ytp-remote",N:[{D:"div",J:"ytp-remote-display-status",N:[{D:"div",J:"ytp-remote-display-status-icon",N:[g.Nma()]},{D:"div",J:"ytp-remote-display-status-text",Y:"{{statustext}}"}]}]});this.api=a;this.i=new g.JM(this,250);g.D(this,this.i);this.L(a,"presentingplayerstatechange",this.l);JJa(this,a.Sa())},JJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.BK("Error on $RECEIVER_NAME",c):b.Ib()||g.U(b,4)?g.BK("Playing on $RECEIVER_NAME",c):g.BK("Connected to $RECEIVER_NAME",c);a.xa("statustext",c);a.i.show()}else a.i.hide()},n7=function(a,b){g.wR.call(this,"Play on",0,a,b);
this.F=a;this.Pl={};this.L(a,"onMdxReceiversChange",this.C);this.L(a,"presentingplayerstatechange",this.C);this.C()},o7=function(a){g.kO.call(this,a);
this.fi={key:D4(),name:"This computer"};this.nh=null;this.subscriptions=[];this.qz=this.tb=null;this.Pl=[this.fi];this.fl=this.fi;this.Jc=new g.aL(64);this.vE=0;this.Ke=-1;this.bp=null;this.Jr=this.ou=!1;this.xn=this.tp=null;if(!g.TC(this.player.P())){a=this.player;var b=g.RN(a);b&&(b=b.an())&&(b=new n7(a,b),g.D(this,b));b=new m7(a);g.D(this,b);g.aO(a,b.element,4);this.tp=new l7;g.D(this,this.tp);g.aO(a,this.tp.element,4);g.Q(this.player.P().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.Q(this.player.P().experiments,"deprecate_pair_servlet_enabled")&&(this.bp=new k7,g.D(this,this.bp),g.aO(a,this.bp.element,4));this.Jr=!!V6();this.ou=!!g.Gu("yt-remote-manual-pairing-warning-shown")}},p7=function(a){a.xn&&(a.player.removeEventListener("presentingplayerstatechange",a.xn),a.xn=null)},KJa=function(a,b,c){a.Jc=c;
a.player.S("presentingplayerstatechange",new g.hK(c,b))},LJa=function(a,b,c){var d=!1;
1===b?d=!a.Jr:2===b&&(d=!a.ou);d&&g.jK(c,8)&&(a.player.pauseVideo(),p7(a))},q7=function(a,b){if(b.key!==a.fl.key)if(b.key===a.fi.key)a7();
else{if(a.bp&&!a.ou&&b!==a.fi&&"cast-selector-receiver"!==b.key&&g.mD(a.player.P()))MJa(a);else{var c;(c=!g.Q(a.player.P().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.Jr||!a.tp);(c?0:g.mD(a.player.P())||g.qD(a.player.P()))&&NJa(a)}a.fl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.P().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Ka(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.fa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=$Ga(c))&&(d.locationInfo=c);c=d}S6("Connecting to: "+g.Pj(b));"cast-selector-receiver"==b.key?(U6(c||null),c=c||null,
n6()?k6().setLaunchParams(c):i6("setLaunchParams called before ready.")):!c&&d7()&&R6()==b.key?x4("yt-remote-connection-change",!0):(a7(),U6(c||null),c=Q6().Pg(),(c=F4(c,b.key))&&b7(c,1))}},NJa=function(a){a.player.Sa().Ib()?a.player.pauseVideo():(a.xn=function(b){LJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.xn));
a.tp&&a.tp.zc();Y6()||(f7=!0)},MJa=function(a){a.player.Sa().Ib()?a.player.pauseVideo():(a.xn=function(b){LJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.xn));
a.bp&&a.bp.zc();Y6()||(f7=!0)},NHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},d5={"'":"\\'"},OJa={},iHa={aS:"atp",q1:"ska",o0:"que",wZ:"mus",o1:"sus",PV:"dsp",G0:"seq",bZ:"mic",PU:"dpa"},L4,H4="",BHa=xHa("loadCastFramework")||xHa("loadCastApplicationFramework"),bJa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ra(O4,g.C);g.k=O4.prototype;g.k.Og=function(a){this.B=arguments;this.i=!1;this.bb?this.u=g.B()+this.Gf:this.bb=g.Lm(this.C,this.Gf)};
g.k.stop=function(){this.bb&&(g.z.clearTimeout(this.bb),this.bb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.aa=function(){this.stop();O4.Bd.aa.call(this)};
g.k.EJ=function(){this.u?(this.bb=g.Lm(this.C,this.u-g.B()),this.u=null):(this.bb=null,this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B)))};g.u(P4,g.C);g.k=P4.prototype;g.k.Og=function(a){this.u=arguments;this.bb||this.l?this.i=!0:Q4(this)};
g.k.stop=function(){this.bb&&(g.z.clearTimeout(this.bb),this.bb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.bb||(this.i=!1,Q4(this))};
g.k.aa=function(){g.C.prototype.aa.call(this);this.stop()};S4.prototype.stringify=function(a){return g.z.JSON.stringify(a,void 0)};
S4.prototype.parse=function(a){return g.z.JSON.parse(a,void 0)};var U4=new g.am;g.u(EHa,g.Hl);W4.prototype.i=null;W4.prototype.getOptions=function(){var a;(a=this.i)||(a={},GHa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var r7;g.Ra(FHa,W4);r7=new FHa;g.k=X4.prototype;g.k.mm=null;g.k.zi=!1;g.k.Lp=null;g.k.BA=null;g.k.wp=null;g.k.Gp=null;g.k.Xk=null;g.k.Rl=null;g.k.yn=null;g.k.ye=null;g.k.Fs=0;g.k.Di=null;g.k.Dv=null;g.k.Rk=null;g.k.aq=-1;g.k.FG=!0;g.k.Jm=!1;g.k.tw=0;g.k.Qu=null;var LHa={},$4={};g.k=X4.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.fQ=function(a){a=a.target;var b=this.Qu;b&&3==i5(a)?b.Og():this.CH(a)};
g.k.CH=function(a){try{if(a==this.ye)a:{var b=i5(this.ye),c=this.ye.G,d=this.ye.getStatus();if(g.ve&&!g.Yd(10)||g.xe&&!g.Xd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yg&&!k5(this.ye))break a;this.Jm||4!=b||7==c||(8==c||0>=d?this.i.ii(3):this.i.ii(2));e5(this);var e=this.ye.getStatus();this.aq=e;var f=k5(this.ye);(this.zi=200==e)?(4==b&&b5(this),this.G?(MHa(this,b,f),g.yg&&this.zi&&3==b&&(this.B.va(this.u,"tick",this.YP),this.u.start())):a5(this,f),this.zi&&!this.Jm&&(4==b?this.i.Us(this):(this.zi=
!1,Z4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Rk=3,V4(13)):(this.Rk=0,V4(14)),b5(this),c5(this))}}catch(h){this.ye&&k5(this.ye)}finally{}};
g.k.YP=function(){var a=i5(this.ye),b=k5(this.ye);this.Fs<b.length&&(e5(this),MHa(this,a,b),this.zi&&4!=a&&Z4(this))};
g.k.xP=function(a){T4((0,g.A)(this.wP,this,a),0)};
g.k.wP=function(a){this.Jm||(e5(this),a5(this,a),Z4(this))};
g.k.QF=function(a){T4((0,g.A)(this.vP,this,a),0)};
g.k.vP=function(a){this.Jm||(b5(this),this.zi=a,this.i.Us(this),this.i.ii(4))};
g.k.cancel=function(){this.Jm=!0;b5(this)};
g.k.FP=function(){this.Lp=null;var a=g.B();0<=a-this.BA?(2!=this.Gp&&this.i.ii(3),b5(this),this.Rk=2,V4(18),c5(this)):PHa(this,this.BA-a)};
g.k.getLastError=function(){return this.Rk};g.Ra(g5,g.am);var WHa=/^https?$/i,PJa=["POST","PUT"];g.k=g5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.T+"; newUri="+a);b=b?b.toUpperCase():"GET";this.T=a;this.u="";this.G=0;this.wa=b;this.da=!1;this.B=!0;this.i=this.ba?HHa(this.ba):HHa(r7);this.Z=this.ba?this.ba.getOptions():r7.getOptions();this.i.onreadystatechange=(0,g.A)(this.EF,this);try{w4(j5(this,"Opening Xhr")),this.ha=!0,this.i.open(b,String(a),!0),this.ha=!1}catch(f){w4(j5(this,"Error opening Xhr: "+f.message));VHa(this,f);return}a=
c||"";var e=this.headers.clone();d&&eHa(d,function(f,h){e.set(h,f)});
d=g.$a(e.uh(),THa);c=g.z.FormData&&a instanceof g.z.FormData;!g.db(PJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Aa&&(this.i.responseType=this.Aa);"withCredentials"in this.i&&this.i.withCredentials!==this.fa&&(this.i.withCredentials=this.fa);try{YHa(this),0<this.I&&(this.V=SHa(this.i),w4(j5(this,"Will abort after "+this.I+"ms if incomplete, xhr2 "+this.V)),this.V?(this.i.timeout=this.I,this.i.ontimeout=(0,g.A)(this.CB,this)):this.U=g.Lm(this.CB,this.I,this)),w4(j5(this,"Sending request")),this.K=!0,this.i.send(a),this.K=!1}catch(f){w4(j5(this,"Send error: "+f.message)),VHa(this,f)}};
g.k.CB=function(){"undefined"!=typeof g.x_&&this.i&&(this.u="Timed out after "+this.I+"ms, aborting",this.G=8,j5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(j5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),h5(this))};
g.k.aa=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),h5(this,!0));g5.Bd.aa.call(this)};
g.k.EF=function(){this.ka()||(this.ha||this.K||this.C?XHa(this):this.EO())};
g.k.EO=function(){XHa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==i5(this)};
g.k.getStatus=function(){try{return 2<i5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=ZHa.prototype;g.k.uw=null;g.k.Bg=null;g.k.Ru=!1;g.k.DB=null;g.k.zt=null;g.k.Ky=null;g.k.ww=null;g.k.Ja=null;g.k.Nj=-1;g.k.bq=null;g.k.lq=null;g.k.connect=function(a){this.ww=a;a=l5(this.i,null,this.ww);V4(3);this.DB=g.B();var b=this.i.I;null!=b?(this.bq=b[0],(this.lq=b[1])?(this.Ja=1,$Ha(this)):(this.Ja=2,n5(this))):(u4(a,"MODE","init"),this.Bg=new X4(this,void 0,void 0,void 0),this.Bg.mm=this.uw,Y4(this.Bg,a,!1,null,!0),this.Ja=0)};
g.k.wK=function(a){if(a)this.Ja=2,n5(this);else{V4(4);var b=this.i;b.Li=b.bl.Nj;u5(b,9)}a&&this.ii(2)};
g.k.xx=function(a){return this.i.xx(a)};
g.k.abort=function(){this.Bg&&(this.Bg.cancel(),this.Bg=null);this.Nj=-1};
g.k.BB=function(){return!1};
g.k.HF=function(a,b){this.Nj=a.aq;if(0==this.Ja)if(b){try{var c=this.l.parse(b)}catch(d){c=this.i;c.Li=this.Nj;u5(c,2);return}this.bq=c[0];this.lq=c[1]}else c=this.i,c.Li=this.Nj,u5(c,2);else if(2==this.Ja)if(this.Ru)V4(7),this.Ky=g.B();else if("11111"==b){if(V4(6),this.Ru=!0,this.zt=g.B(),c=this.zt-this.DB,!g.ve||g.Yd(10)||500>c)this.Nj=200,this.Bg.cancel(),V4(12),m5(this.i,this,!0)}else V4(8),this.zt=this.Ky=g.B(),this.Ru=!1};
g.k.Us=function(){this.Nj=this.Bg.aq;if(this.Bg.zi)0==this.Ja?this.lq?(this.Ja=1,$Ha(this)):(this.Ja=2,n5(this)):2==this.Ja&&((!g.ve||g.Yd(10)?!this.Ru:200>this.Ky-this.zt)?(V4(11),m5(this.i,this,!1)):(V4(12),m5(this.i,this,!0)));else{0==this.Ja?V4(9):2==this.Ja&&V4(10);var a=this.i;this.Bg.getLastError();a.Li=this.Nj;u5(a,2)}};
g.k.ds=function(){return this.i.ds()};
g.k.isActive=function(){return this.i.isActive()};
g.k.ii=function(a){this.i.ii(a)};g.k=o5.prototype;g.k.Ki=null;g.k.Fq=null;g.k.ng=null;g.k.Wd=null;g.k.xw=null;g.k.At=null;g.k.sC=null;g.k.Vs=null;g.k.yr=0;g.k.uM=0;g.k.wf=null;g.k.ol=null;g.k.Qj=null;g.k.Rm=null;g.k.bl=null;g.k.Bv=null;g.k.Vo=-1;g.k.uE=-1;g.k.Li=-1;g.k.Bo=0;g.k.ko=0;g.k.Km=8;g.Ra(bIa,g.Hl);g.Ra(cIa,g.Hl);g.k=o5.prototype;g.k.connect=function(a,b,c,d,e){V4(0);this.xw=b;this.Fq=c||{};d&&void 0!==e&&(this.Fq.OSID=d,this.Fq.OAID=e);this.C?(T4((0,g.A)(this.KC,this,a),100),gIa(this)):this.KC(a)};
g.k.KC=function(a){this.bl=new ZHa(this);this.bl.uw=this.Ki;this.bl.l=this.B;this.bl.connect(a)};
g.k.BB=function(){return 0==this.Ja};
g.k.getState=function(){return this.Ja};
g.k.OF=function(a){this.ol=null;kIa(this,a)};
g.k.NF=function(){this.Qj=null;this.Wd=new X4(this,this.l,"rpc",this.G);this.Wd.mm=this.Ki;this.Wd.tw=0;var a=this.sC.clone();s4(a,"RID","rpc");s4(a,"SID",this.l);s4(a,"CI",this.Bv?"0":"1");s4(a,"AID",this.Vo);p5(this,a);if(!g.ve||g.Yd(10))s4(a,"TYPE","xmlhttp"),Y4(this.Wd,a,!0,this.Vs,!1);else{s4(a,"TYPE","html");var b=this.Wd,c=!!this.Vs;b.Gp=3;b.Xk=t4(a.clone());OHa(b,c)}};
g.k.HF=function(a,b){if(0!=this.Ja&&(this.Wd==a||this.ng==a))if(this.Li=a.aq,this.ng==a&&3==this.Ja)if(7<this.Km){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Qj){if(this.Wd)if(this.Wd.wp+3E3<this.ng.wp)r5(this),this.Wd.cancel(),this.Wd=null;else break a;t5(this);V4(19)}}else this.uE=c[1],0<this.uE-this.Vo&&37500>c[2]&&this.Bv&&0==this.ko&&!this.Rm&&(this.Rm=T4((0,g.A)(this.aN,this),6E3));else u5(this,11)}else b!=OJa.EU.i&&u5(this,11);else if(this.Wd==
a&&r5(this),!g.mc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Vo=e[0];e=e[1];2==this.Ja?"c"==e[0]?(this.l=e[1],this.Vs=e[2],e=e[3],null!=e?this.Km=e:this.Km=6,this.Ja=3,this.wf&&this.wf.GC(),this.sC=l5(this,this.ds()?this.Vs:null,this.xw),lIa(this)):"stop"==e[0]&&u5(this,7):3==this.Ja&&("stop"==e[0]?u5(this,7):"noop"!=e[0]&&this.wf&&this.wf.FC(e),this.ko=0)}}};
g.k.aN=function(){null!=this.Rm&&(this.Rm=null,this.Wd.cancel(),this.Wd=null,t5(this),V4(20))};
g.k.Us=function(a){if(this.Wd==a){r5(this);this.Wd=null;var b=2}else if(this.ng==a)this.ng=null,b=1;else return;this.Li=a.aq;if(0!=this.Ja)if(a.zi)1==b?(b=U4,b.dispatchEvent(new bIa(b,a.yn?a.yn.length:0,g.B()-a.wp,this.Bo)),q5(this),this.u.length=0):lIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Li)){if(d=1==b)this.ng||this.ol||1==this.Ja||2<=this.Bo?d=!1:(this.ol=T4((0,g.A)(this.OF,this,a),mIa(this,this.Bo)),this.Bo++,d=!0);d=!(d||2==b&&t5(this))}if(d)switch(c){case 1:u5(this,
5);break;case 4:u5(this,10);break;case 3:u5(this,6);break;case 7:u5(this,12);break;default:u5(this,2)}}};
g.k.SK=function(a){if(!g.db(arguments,this.Ja))throw Error("Unexpected channel state: "+this.Ja);};
g.k.NQ=function(a){a?V4(2):(V4(1),nIa(this,8))};
g.k.xx=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g5;a.fa=!1;return a};
g.k.isActive=function(){return!!this.wf&&this.wf.isActive(this)};
g.k.ii=function(a){var b=U4;b.dispatchEvent(new cIa(b,a))};
g.k.ds=function(){return!(!g.ve||g.Yd(10))};
g.k=oIa.prototype;g.k.GC=function(){};
g.k.FC=function(){};
g.k.EC=function(){};
g.k.gx=function(){};
g.k.pD=function(){return{}};
g.k.isActive=function(){return!0};g.k=pIa.prototype;g.k.isEmpty=function(){return g.eb(this.i)&&g.eb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.db(this.i,a)||g.db(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.yBa)(b,a);0<=c?(g.gb(b,c),b=!0):b=!1;return b||g.ib(this.l,a)};
g.k.qg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ra(v5,g.C);g.k=v5.prototype;g.k.pP=function(){this.Gf=Math.min(3E5,2*this.Gf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Gf+15E3*Math.random();g.kn(this.i,a);this.l=g.B()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Gf=5E3};g.Ra(w5,oIa);g.k=w5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Mf=function(a){return this.u.Mf(a)};
g.k.S=function(a,b){return this.u.S.apply(this.u,arguments)};
g.k.dispose=function(){this.U||(this.U=!0,g.Yf(this.u),sIa(this),g.Yf(this.l),this.l=null,this.V=function(){return""})};
g.k.ka=function(){return this.U};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.T="";this.l.stop();this.C=a||null;this.B=b||0;a=this.Z+"/test";b=this.Z+"/bind";var d=new o5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ba),e=this.i;e&&(e.wf=null);d.wf=this;this.i=d;x5(this);if(this.i){d=g.M("ID_TOKEN");var f=this.i.Ki||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Ki=f}e?(3!=e.getState()&&0==iIa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.Vo)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Tb(c,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.I.push(c):y5(this)&&(x5(this),hIa(this.i,c))};
g.k.GC=function(){this.l.reset();this.C=null;this.B=0;if(this.I.length){var a=this.I;this.I=[];for(var b=0,c=a.length;b<c;++b)hIa(this.i,a[b])}this.S("handlerOpened")};
g.k.EC=function(a){var b=2==a&&401==this.i.Li;4==a||b||this.l.start();this.S("handlerError",a,b)};
g.k.gx=function(a){if(!this.l.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.I.push(d)}};
g.k.pD=function(){var a={v:2};this.T&&(a.gsessionid=this.T);0!=this.B&&(a.ui=""+this.B);0!=this.K&&(a.ui=""+this.K);this.C&&g.Tb(a,this.C);return a};
g.k.FC=function(a){"S"==a[0]?this.T=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),fIa(this.i)):this.S("handlerMessage",new qIa(a[0],a[1]))};
g.k.av=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.fa&&this.i){var b=this.i.Ki||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Ki=b}};
g.k.qQ=function(){this.l.isActive();0==iIa(this.i)&&this.connect(this.C,this.B)};z5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
z5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
z5.prototype.C=function(a){a(Error("request timed out"))};var zIa=g.B(),C5=null,G5=Array(50),F5=-1,H5=!1;g.Ra(I5,g.O);I5.prototype.Pg=function(){return this.screens};
I5.prototype.contains=function(a){return!!E4(this.screens,a)};
I5.prototype.get=function(a){return a?F4(this.screens,a):null};
I5.prototype.info=function(a){D5(this.G,a)};g.u(J5,g.O);g.k=J5.prototype;g.k.start=function(){!this.i&&isNaN(this.bb)&&this.bG()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.bb)||(g.Do(this.bb),this.bb=NaN)};
g.k.aa=function(){this.stop();g.O.prototype.aa.call(this)};
g.k.bG=function(){this.bb=NaN;this.i=g.$p(A5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.G},timeout:5E3,onSuccess:(0,g.A)(this.GJ,this),onError:(0,g.A)(this.FJ,this),onTimeout:(0,g.A)(this.HJ,this)})};
g.k.GJ=function(a,b){this.i=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.S("pairingComplete",new z4(c))};
g.k.FJ=function(a){this.i=null;a.status&&404==a.status?this.l>=QJa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=QJa[this.l],this.bb=g.Bo((0,g.A)(this.bG,this),a),this.l++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.HJ=function(){this.i=null;this.S("pairingFailed",Error("Server not responding"))};
var QJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ra(L5,I5);g.k=L5.prototype;g.k.start=function(){K5(this)&&this.S("screenChange");!g.Gu("yt-remote-lounge-token-expiration")&&DIa(this);g.Do(this.i);this.i=g.Bo((0,g.A)(this.start,this),1E4)};
g.k.add=function(a,b){K5(this);AIa(this,a);M5(this,!1);this.S("screenChange");b(a);a.token||DIa(this)};
g.k.remove=function(a,b){var c=K5(this);CIa(this,a)&&(M5(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.zv=function(a,b,c,d){var e=K5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,M5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.aa=function(){g.Do(this.i);L5.Bd.aa.call(this)};
g.k.tL=function(a){K5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}M5(this,!b);b&&D5(this.G,"Missed "+b+" lounge tokens.")};
g.k.sL=function(a){D5(this.G,"Requesting lounge tokens failed: "+a)};g.u(O5,g.O);g.k=O5.prototype;g.k.start=function(){var a=parseInt(g.Gu("yt-remote-fast-check-period")||"0",10);(this.B=g.B()-144E5<a?0:a)?R5(this):(this.B=g.B()+3E5,g.Fu("yt-remote-fast-check-period",this.B),this.Cz())};
g.k.isEmpty=function(){return g.Mb(this.i)};
g.k.update=function(){N5("Updating availability on schedule.");var a=this.G(),b=g.Bb(this.i,function(c,d){return c&&!!F4(a,d)},this);
Q5(this,b)};
g.k.aa=function(){g.Do(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.O.prototype.aa.call(this)};
g.k.Cz=function(){g.Do(this.u);this.u=NaN;this.l&&this.l.abort();var a=FIa(this);if(v4(a)){var b=A5(this.C,"/pairing/get_screen_availability");this.l=B5(this.C,b,{lounge_token:g.Hb(a).join(",")},(0,g.A)(this.YO,this,a),(0,g.A)(this.XO,this))}else Q5(this,{}),R5(this)};
g.k.YO=function(a,b){this.l=null;var c=g.Hb(FIa(this));if(g.wb(c,g.Hb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Q5(this,d);R5(this)}else this.Cd("Changing Screen set during request."),this.Cz()};
g.k.XO=function(a){this.Cd("Screen availability failed: "+a);this.l=null;R5(this)};
g.k.Cd=function(a){D5("OnlineScreenService",a)};g.Ra(S5,I5);g.k=S5.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.S("screenChange"),this.i.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.zv=function(a,b,c,d){this.l.contains(a)?this.l.zv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,D5(this.G,a),d(Error(a)))};
g.k.Pg=function(a){return a?this.screens:g.kb(this.screens,g.He(this.u,function(b){return!this.contains(b)},this))};
g.k.EB=function(){return g.He(this.Pg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.FB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new J5(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(h){g.Yf(f);d(T5(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Yf(f);e(h)});
f.start();return(0,g.A)(f.stop,f)};
g.k.IJ=function(a,b,c,d){g.$p(A5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(e,f){var h=new z4(f.screen||{});if(!h.name||JIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);JIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(T5(this,h))},this),
onError:(0,g.A)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.k.aa=function(){g.Yf(this.l);g.Yf(this.i);S5.Bd.aa.call(this)};
g.k.zL=function(){LIa(this);this.S("screenChange");this.i.update()};
S5.prototype.dispose=S5.prototype.dispose;g.Ra(V5,g.O);g.k=V5.prototype;g.k.getScreen=function(){return this.u};
g.k.Zf=function(a){this.ka()||(a&&X5(this,""+a),this.u=null,this.S("sessionScreen",null))};
g.k.info=function(a){D5(this.fa,a)};
g.k.GB=function(){return null};
g.k.Oz=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){X5(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.aa=function(){this.Oz("");V5.Bd.aa.call(this)};g.u(Y5,V5);g.k=Y5.prototype;g.k.Nz=function(a){if(this.l){if(this.l==a)return;X5(this,"Overriding cast session with new session object");TIa(this);this.ba=!1;this.T="unknown";this.l.removeUpdateListener(this.V);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z)}this.l=a;this.l.addUpdateListener(this.V);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z);PIa(this,"getMdxSessionStatus")};
g.k.Wo=function(a){this.info("launchWithParams no-op for Cast: "+g.Pj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.A)(function(){this.Zf()},this),(0,g.A)(function(){this.Zf(Error("Failed to stop receiver app."))},this)):this.Zf(Error("Stopping cast device without session."))};
g.k.Oz=function(){};
g.k.aa=function(){this.info("disposeInternal");TIa(this);this.l&&(this.l.removeUpdateListener(this.V),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z));this.l=null;V5.prototype.aa.call(this)};
g.k.MP=function(a,b){if(!this.ka())if(b){var c=R4(b);if(g.Ma(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Pj(c));switch(d){case "mdxSessionStatus":NIa(this,c);break;case "loungeToken":QIa(this,c);break;default:X5(this,"Unknown youtube message: "+d)}}else X5(this,"Unable to parse message.")}else X5(this,"No data in message.")};
g.k.GD=function(a,b,c,d){g.Do(this.K);this.K=0;IIa(this.B,this.i.label,a,this.i.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(X5(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.K=g.Bo((0,g.A)(this.GD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.GB=function(){return this.l};
g.k.JJ=function(a){this.ka()||a||(X5(this,"Cast session died."),this.Zf())};g.u(a6,V5);g.k=a6.prototype;g.k.Nz=function(a){this.C=a;this.C.addUpdateListener(this.U)};
g.k.Wo=function(a){this.V=a;this.I()};
g.k.stop=function(){this.l();this.l=g.Ia;g.Do(this.G);this.C?this.C.stop((0,g.A)(this.Zf,this,null),(0,g.A)(this.Zf,this,"Failed to stop DIAL device.")):this.Zf()};
g.k.aa=function(){this.l();this.l=g.Ia;g.Do(this.G);this.C&&this.C.removeUpdateListener(this.U);this.C=null;V5.prototype.aa.call(this)};
g.k.KJ=function(a){this.ka()||a||(X5(this,"DIAL session died."),this.l(),this.l=g.Ia,this.Zf())};
g.k.wy=function(a){this.T=D4();if(this.V){var b=new chrome.cast.DialLaunchResponse(!0,VIa(this));a(b);UIa(this)}else this.I=(0,g.A)(function(){g.Do(this.G);this.I=g.Ia;this.G=NaN;var c=new chrome.cast.DialLaunchResponse(!0,VIa(this));a(c);UIa(this)},this),this.G=g.Bo((0,g.A)(function(){this.I()},this),100)};
g.k.QL=function(a,b,c){IIa(this.B,this.K.receiver.label,a,this.i.friendlyName,(0,g.A)(function(d){d&&d.token?(W5(this,d),b(new chrome.cast.DialLaunchResponse(!1))):this.wy(b,c)},this),(0,g.A)(function(d){X5(this,"Failed to get DIAL screen: "+d);
this.wy(b,c)},this))};g.u(b6,V5);b6.prototype.stop=function(){this.Zf()};
b6.prototype.Nz=function(){};
b6.prototype.Wo=function(){g.Do(this.l);this.l=NaN;var a=F4(this.B.Pg(),this.i.label);a?W5(this,a):this.Zf(Error("No such screen"))};
b6.prototype.aa=function(){g.Do(this.l);this.l=NaN;V5.prototype.aa.call(this)};g.u(c6,g.O);g.k=c6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.T||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.A)(this.IO,this);c=new chrome.cast.ApiConfig(c,(0,g.A)(this.JF,this),f,d,e);c.customDialLaunchCallback=(0,g.A)(this.vN,this);chrome.cast.initialize(c,(0,g.A)(function(){this.ka()||
(chrome.cast.addReceiverActionListener(this.G),wIa(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.HB,this)),this.u=XIa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.A)(function(h){this.Cd("Failed to set initial custom receivers: "+g.Pj(h))},this)),this.S("yt-remote-cast2-availability-change",e6(this)),b(!0))},this),(0,g.A)(function(h){this.Cd("Failed to initialize API: "+g.Pj(h));
b(!1)},this))};
g.k.xQ=function(a,b){d6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)d6("Unsetting old screen status: "+this.i.i.friendlyName),f6(this,null)}if(a&&b){if(!this.i){c=F4(this.l.Pg(),a);if(!c){d6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){d6("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=WIa(this,c);d||(d6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(d),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.A)(function(e){this.Cd("Failed to set initial custom receivers: "+g.Pj(e))},this)));
d6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);f6(this,new b6(this.l,d),!0)}this.i.Oz(b)}else d6("setConnectedScreenStatus: no screen.")};
g.k.yQ=function(a){this.ka()?this.Cd("Setting connection data on disposed cast v2"):this.i?this.i.Wo(a):this.Cd("Setting connection data without a session")};
g.k.MJ=function(){this.ka()?this.Cd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),f6(this,null)):d6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.JF,this),(0,g.A)(this.bP,this))};
g.k.aa=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.HB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=tIa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.ib(b||[],a);g.Yf(this.i);g.O.prototype.aa.call(this)};
g.k.Cd=function(a){D5("Controller",a)};
g.k.LF=function(a,b){this.i==a&&(b||f6(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.FO=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),d6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)d6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{d6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.S("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:f6(this,
new b6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:f6(this,new a6(this.l,a,this.C));break;case chrome.cast.ReceiverType.CAST:f6(this,new Y5(this.l,a,this.B));break;default:this.Cd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Cd("Stopping receiver w/o session: "+a.friendlyName)}else this.Cd("onReceiverAction_ called without receiver.")};
g.k.vN=function(a){if(this.ka())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Cd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Cd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return d6("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Cd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);f6(this,new a6(this.l,b,this.C))}b=this.i;b.K=a;return b.K.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.QL,b,(b.K.extraData||{}).screenId||null)):new Promise((0,g.A)(b.wy,b))};
g.k.JF=function(a){if(!this.ka()){d6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)d6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),f6(this,new Y5(this.l,b,this.B),!0);else{this.Cd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=F4(this.l.Pg(),c.label);d&&A4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(d6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Yf(this.i),this.i=new Y5(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.A)(this.LF,this,this.i)),this.i.Wo(null));this.i.Nz(a)}}};
g.k.LJ=function(){return this.i?this.i.GB():null};
g.k.bP=function(a){this.ka()||(this.Cd("Failed to estabilish a session: "+g.Pj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&f6(this,null))};
g.k.IO=function(a){d6("Receiver availability updated: "+a);if(!this.ka()){var b=e6(this);this.I=a==chrome.cast.ReceiverAvailability.AVAILABLE;e6(this)!=b&&this.S("yt-remote-cast2-availability-change",e6(this))}};
g.k.HB=function(){this.ka()||(this.u=XIa(this),d6("Updating custom receivers: "+g.Pj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.A)(function(){this.Cd("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",e6(this)))};
c6.prototype.setLaunchParams=c6.prototype.yQ;c6.prototype.setConnectedScreenStatus=c6.prototype.xQ;c6.prototype.stopSession=c6.prototype.MJ;c6.prototype.getCastSession=c6.prototype.LJ;c6.prototype.requestSession=c6.prototype.requestSession;c6.prototype.init=c6.prototype.init;c6.prototype.dispose=c6.prototype.dispose;var l6=[];g.k=q6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";r6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.i=a.trackData,this.hj=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.l=a.seekableEnd,this.G=a.duration,this.T=a.loadedTime,this.B=a.liveIngestionTime,this.u=!isNaN(this.B))};
g.k.Ib=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.u?this.G+s6(this):this.G};
g.k.clone=function(){return new q6(w6(this))};g.u(y6,g.O);g.k=y6.prototype;g.k.getState=function(){return this.Ja};
g.k.play=function(){A6(this)?(this.i?this.i.play(null,g.Ia,F6(this,"play")):E6(this,"play"),D6(this,1,u6(z6(this))),this.S("remotePlayerChange")):B6(this,this.play)};
g.k.pause=function(){A6(this)?(this.i?this.i.pause(null,g.Ia,F6(this,"pause")):E6(this,"pause"),D6(this,2,u6(z6(this))),this.S("remotePlayerChange")):B6(this,this.pause)};
g.k.seekTo=function(a){if(A6(this)){if(this.i){var b=z6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Ib()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,F6(this,"seekTo",{newTime:a}))}else E6(this,"seekTo",{newTime:a});D6(this,3,a);this.S("remotePlayerChange")}else B6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(A6(this)){this.i?this.i.stop(null,g.Ia,F6(this,"stopVideo")):E6(this,"stopVideo");var a=z6(this);a.index=-1;a.videoId="";r6(a);C6(this,a);this.S("remotePlayerChange")}else B6(this,this.stop)};
g.k.setVolume=function(a,b){if(A6(this)){var c=z6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.A)(function(){E5("set receiver volume: "+d)},this),(0,g.A)(function(){this.Cd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.A)(function(){E5("set receiver muted: "+b)},this),(0,g.A)(function(){this.Cd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);E6(this,"setVolume",e)}c.muted=b;c.volume=a;C6(this,c)}else B6(this,g.Pa(this.setVolume,a,b))};
g.k.IB=function(a,b){if(A6(this)){var c=z6(this),d={videoId:a};b&&(c.i={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Pj(b.style),g.Tb(d,c.i));E6(this,"setSubtitlesTrack",d);C6(this,c)}else B6(this,g.Pa(this.IB,a,b))};
g.k.setAudioTrack=function(a,b){if(A6(this)){var c=b.getLanguageInfo().getId();E6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=z6(this);d.audioTrackId=c;C6(this,d)}else B6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=z6(this);c=c||0;var m={videoId:a,currentIndex:c};v6(l,a,c);void 0!==b&&(t6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Pj(h));E6(this,"setPlaylist",m);d||C6(this,l)};
g.k.Mu=function(a,b){if(A6(this)){if(a&&b){var c=z6(this);v6(c,a,b);C6(this,c)}E6(this,"previous")}else B6(this,g.Pa(this.Mu,a,b))};
g.k.nextVideo=function(a,b){if(A6(this)){if(a&&b){var c=z6(this);v6(c,a,b);C6(this,c)}E6(this,"next")}else B6(this,g.Pa(this.nextVideo,a,b))};
g.k.YC=function(){A6(this)?E6(this,"dismissAutoplay"):B6(this,this.YC)};
g.k.dispose=function(){if(3!=this.Ja){var a=this.Ja;this.Ja=3;this.S("proxyStateChange",a,this.Ja)}g.O.prototype.dispose.call(this)};
g.k.aa=function(){jJa(this);this.u=null;this.B.clear();x6(this,null);g.O.prototype.aa.call(this)};
g.k.Rz=function(a){if((a!=this.Ja||2==a)&&3!=this.Ja&&0!=a){var b=this.Ja;this.Ja=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.eb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.CO=function(a,b){this.S(a,b)};
g.k.hN=function(a){if(!a)this.Ar(null),x6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=z6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)E5("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,C6(this,b)}};
g.k.Ar=function(a){E5("Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.I);if(this.i=a)this.i.addUpdateListener(this.I),kJa(this),this.S("remotePlayerChange")};
g.k.gN=function(a){a?(kJa(this),this.S("remotePlayerChange")):this.Ar(null)};
g.k.hA=function(){E6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.oN=function(){var a=gJa();a&&x6(this,a)};
g.k.Cd=function(a){D5("CP",a)};g.u(G6,g.O);g.k=G6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Cb.listId=c);this.Cb.videoId=d;this.Cb.index=h||0;this.Cb.state=3;t6(this.Cb,m);this.B="UNSUPPORTED";H6("Connecting with setPlaylist and params: "+g.Pj(l));this.i.connect({method:"setPlaylist",
params:g.Pj(l)},a,qHa())}else H6("Connecting without params"),this.i.connect({},a,qHa());mJa(this)};
g.k.av=function(a){this.i.av(a)};
g.k.dispose=function(){this.ka()||(this.S("beforeDispose"),I6(this,3));g.O.prototype.dispose.call(this)};
g.k.aa=function(){J6(this);L6(this);K6(this);g.Do(this.I);this.I=NaN;g.Do(this.K);this.K=NaN;this.u=null;g.dp(this.T);this.T.length=0;this.i.dispose();g.O.prototype.aa.call(this);this.B=this.G=this.l=this.Cb=this.i=null};
g.k.nL=function(){this.xo(2)};
g.k.lN=function(){H6("Channel opened");this.Z&&(this.Z=!1,K6(this),this.V=g.Bo((0,g.A)(function(){H6("Timing out waiting for a screen.");this.xo(1)},this),15E3));
uHa(rIa(this.i),this.da)};
g.k.iN=function(){H6("Channel closed");isNaN(this.C)?K4(!0):K4();this.dispose()};
g.k.jN=function(a,b){K4();isNaN(this.Wq())?(b&&"shortLived"==this.ba&&this.S("browserChannelAuthError",a),H6("Channel error: "+a+" without reconnection"),this.dispose()):(this.Z=!0,H6("Channel error: "+a+" with reconnection in "+this.Wq()+" ms"),I6(this,2))};
g.k.kN=function(a){a.params?H6("Received: action="+a.action+", params="+g.Pj(a.params)):H6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=R4(a.params.devices);this.l=g.Jc(a,function(c){return new y4(c)});
a=!!g.$a(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
pJa(this,a);break;case "loungeScreenDisconnected":g.jb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
pJa(this,!1);break;case "remoteConnected":var b=new y4(R4(a.params.device));g.$a(this.l,function(c){return b?c.id==b.id:!1})||aHa(this.l,b);
break;case "remoteDisconnected":b=new y4(R4(a.params.device));g.jb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":rJa(this,a);break;case "nowPlaying":tJa(this,a);break;case "onStateChange":sJa(this,a);break;case "onAdStateChange":uJa(this,a);break;case "onVolumeChanged":vJa(this,a);break;case "onSubtitlesTrackChanged":qJa(this,a);break;case "nowAutoplaying":wJa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.S("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":xJa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:H6("Unrecognized action: "+a.action)}};
g.k.mQ=function(){if(this.u){var a=this.u;this.u=null;this.Cb.videoId!=a&&M6(this,"getNowPlaying")}};
g.k.iL=function(){var a=3;this.ka()||(a=0,isNaN(this.Wq())?y5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.xo=function(a){H6("Disconnecting with "+a);J6(this);this.S("beforeDisconnect",a);1==a&&K4();sIa(this.i,a);this.dispose()};
g.k.gL=function(){var a=this.Cb;this.u&&(a=this.Cb.clone(),v6(a,this.u,a.index));return w6(a)};
g.k.zQ=function(a){var b=new q6(a);b.videoId&&b.videoId!=this.Cb.videoId&&(this.u=b.videoId,g.Do(this.I),this.I=g.Bo((0,g.A)(this.mQ,this),5E3));var c=[];this.Cb.listId==b.listId&&this.Cb.videoId==b.videoId&&this.Cb.index==b.index||c.push("remoteQueueChange");this.Cb.playerState==b.playerState&&this.Cb.volume==b.volume&&this.Cb.muted==b.muted&&u6(this.Cb)==u6(b)&&g.Pj(this.Cb.i)==g.Pj(b.i)||c.push("remotePlayerChange");this.Cb.reset(a);g.yb(c,function(d){this.S(d)},this)};
g.k.FD=function(){var a=this.i.G.id,b=g.$a(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Wq=function(){var a=this.i;return a.l.isActive()?a.l.l-g.B():NaN};
g.k.cL=function(){return this.B||"UNSUPPORTED"};
g.k.dL=function(){return this.G||""};
g.k.NJ=function(){if(!isNaN(this.Wq())){var a=this.i.l;a.i.Og();a.start()}};
g.k.vQ=function(a,b){M6(this,a,b);oJa(this)};
g.k.JB=function(){var a=g.Uq("SID","")||"",b=g.Uq("SAPISID","")||"",c=g.Uq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.pf(g.Se(a),2);b=g.pf(g.Se(b),2);c=g.pf(g.Se(c),2);return g.pf(g.Se(a+","+b+","+c),2)};
G6.prototype.subscribe=G6.prototype.subscribe;G6.prototype.unsubscribeByKey=G6.prototype.Mf;G6.prototype.getProxyState=G6.prototype.iL;G6.prototype.disconnect=G6.prototype.xo;G6.prototype.getPlayerContextData=G6.prototype.gL;G6.prototype.setPlayerContextData=G6.prototype.zQ;G6.prototype.getOtherConnectedRemoteId=G6.prototype.FD;G6.prototype.getReconnectTimeout=G6.prototype.Wq;G6.prototype.getAutoplayMode=G6.prototype.cL;G6.prototype.getAutoplayVideoId=G6.prototype.dL;G6.prototype.reconnect=G6.prototype.NJ;
G6.prototype.sendMessage=G6.prototype.vQ;G6.prototype.getXsrfToken=G6.prototype.JB;g.u(N6,I5);g.k=N6.prototype;g.k.Pg=function(a){return this.Ff.$_gs(a)};
g.k.contains=function(a){return!!this.Ff.$_c(a)};
g.k.get=function(a){return this.Ff.$_g(a)};
g.k.start=function(){this.Ff.$_st()};
g.k.add=function(a,b,c){this.Ff.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ff.$_r(a,b,c)};
g.k.zv=function(a,b,c,d){this.Ff.$_un(a,b,c,d)};
g.k.aa=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ff.$_ubk(this.i[a]);this.i.length=0;this.Ff=null;I5.prototype.aa.call(this)};
g.k.OJ=function(){this.S("screenChange")};
g.k.jO=function(){this.S("onlineScreenChange")};
S5.prototype.$_st=S5.prototype.start;S5.prototype.$_gspc=S5.prototype.IJ;S5.prototype.$_gsppc=S5.prototype.FB;S5.prototype.$_c=S5.prototype.contains;S5.prototype.$_g=S5.prototype.get;S5.prototype.$_a=S5.prototype.add;S5.prototype.$_un=S5.prototype.zv;S5.prototype.$_r=S5.prototype.remove;S5.prototype.$_gs=S5.prototype.Pg;S5.prototype.$_gos=S5.prototype.EB;S5.prototype.$_s=S5.prototype.subscribe;S5.prototype.$_ubk=S5.prototype.Mf;var $6=null,f7=!1,O6=null,P6=null,e7=null,T6=[];g.u(g7,g.C);g.k=g7.prototype;g.k.aa=function(){g.C.prototype.aa.call(this);this.i.stop();this.u.stop();this.K.stop();this.V();var a=this.tb;a.unsubscribe("proxyStateChange",this.GF,this);a.unsubscribe("remotePlayerChange",this.Gr,this);a.unsubscribe("remoteQueueChange",this.Ju,this);a.unsubscribe("previousNextChange",this.DF,this);a.unsubscribe("nowAutoplaying",this.yF,this);a.unsubscribe("autoplayDismissed",this.YE,this);this.tb=this.l=null};
g.k.KB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.tb.Ja)if(h7(this)){if(!z6(this.tb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":z6(this.tb).Ib()?this.tb.pause():this.tb.play();break;case "control_play":this.tb.play();break;case "control_pause":this.tb.pause();break;case "control_seek":this.I.Og(c[0],c[1]);break;case "control_subtitles_set_track":i7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.F.getCurrentTime();j7(this,0===c?void 0:c);break;case "control_seek":j7(this,c[0]);break;case "control_subtitles_set_track":i7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.eN=function(a){this.K.Og(a)};
g.k.dR=function(a){this.KB("control_subtitles_set_track",g.Mb(a)?null:a)};
g.k.VG=function(){var a=this.F.getOption("captions","track");g.Mb(a)||i7(this,a)};
g.k.xb=function(a){this.l.xb(a,this.F.getVideoData().lengthSeconds)};
g.k.SN=function(){g.Mb(this.B)||IJa(this,this.B);this.C=!1};
g.k.GF=function(a,b){this.u.stop();2===b&&this.QG()};
g.k.Gr=function(){if(h7(this)){this.i.stop();var a=z6(this.tb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Ke=1;break;case 1082:case 1083:this.l.Ke=0;break;default:this.l.Ke=-1}switch(a.playerState){case 1081:case 1:this.qb(new g.aL(8));this.PG();break;case 1085:case 3:this.qb(new g.aL(9));break;case 1083:case 0:this.qb(new g.aL(2));this.I.stop();this.xb(this.F.getVideoData().lengthSeconds);break;case 1084:this.qb(new g.aL(4));break;case 2:this.qb(new g.aL(4));this.xb(u6(a));
break;case -1:this.qb(new g.aL(64));break;case -1E3:this.qb(new g.aL(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=z6(this.tb).i;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,IJa(this,a));a=z6(this.tb);-1===a.volume||Math.round(this.F.getVolume())===a.volume&&this.F.isMuted()===a.muted||this.T.isActive()||this.sH()}else HJa(this)};
g.k.DF=function(){this.F.S("mdxpreviousnextchange")};
g.k.Ju=function(){h7(this)||HJa(this)};
g.k.yF=function(a){isNaN(a)||this.F.S("mdxnowautoplaying",a)};
g.k.YE=function(){this.F.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){h7(this)&&this.tb.setAudioTrack(this.F.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===z6(this.tb).playerState?j7(this,a):b&&this.tb.seekTo(a)};
g.k.sH=function(){var a=this;if(h7(this)){var b=z6(this.tb);this.events.Db(this.U);b.muted?this.F.mute():this.F.unMute();this.F.setVolume(b.volume);this.U=this.events.L(this.F,"onVolumeChange",function(c){GJa(a,c)})}};
g.k.PG=function(){this.i.stop();if(!this.tb.ka()){var a=z6(this.tb);a.Ib()&&this.qb(new g.aL(8));this.xb(u6(a));this.i.start()}};
g.k.QG=function(){this.u.stop();this.i.stop();var a=this.tb.u.getReconnectTimeout();2==this.tb.Ja&&!isNaN(a)&&this.u.start()};
g.k.qb=function(a){this.u.stop();var b=this.G;if(!g.fL(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.F.An(c);this.G=a;KJa(this.l,b,a)}};g.u(k7,g.V);k7.prototype.zc=function(){this.i.show()};
k7.prototype.fb=function(){this.i.hide()};
k7.prototype.l=function(){g.JK("https://support.google.com/youtube/answer/7640706")};
k7.prototype.u=function(){x4("mdx-manual-pairing-popup-ok");this.fb()};g.u(l7,g.V);l7.prototype.zc=function(){this.i.show()};
l7.prototype.fb=function(){this.i.hide()};
l7.prototype.l=function(){x4("mdx-privacy-popup-cancel");this.fb()};
l7.prototype.u=function(){x4("mdx-privacy-popup-confirm");this.fb()};g.u(m7,g.V);m7.prototype.l=function(a){JJa(this,a.state)};g.u(n7,g.wR);n7.prototype.C=function(){var a=this.F.getOption("remote","receivers");a&&1<a.length&&!this.F.getOption("remote","quickCast")?(this.Pl=g.zb(a,this.i,this),g.xR(this,g.Jc(a,this.i)),a=this.F.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.gh(a),this.enable(!0)):this.enable(!1)};
n7.prototype.i=function(a){return a.key};
n7.prototype.Oh=function(a){return"cast-selector-receiver"===a?"Cast...":this.Pl[a].name};
n7.prototype.Te=function(a){g.wR.prototype.Te.call(this,a);this.F.setOption("remote","currentReceiver",this.Pl[a]);this.Ya.fb()};g.u(o7,g.kO);g.k=o7.prototype;
g.k.create=function(){var a=this.player.P(),b=g.RC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.Q(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.Q(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.Q(a.experiments,"enable_cast_short_lived_lounge_token")};BJa(b,a);this.subscriptions.push(g.Io("yt-remote-before-disconnect",this.cN,this));this.subscriptions.push(g.Io("yt-remote-connection-change",this.JO,this));this.subscriptions.push(g.Io("yt-remote-receiver-availability-change",
this.FF,this));this.subscriptions.push(g.Io("yt-remote-auto-connect",this.HO,this));this.subscriptions.push(g.Io("yt-remote-receiver-resumed",this.GO,this));this.subscriptions.push(g.Io("mdx-privacy-popup-confirm",this.bQ,this));this.subscriptions.push(g.Io("mdx-privacy-popup-cancel",this.aQ,this));this.subscriptions.push(g.Io("mdx-manual-pairing-popup-ok",this.iM,this));this.FF()};
g.k.load=function(){this.player.cancelPlayback();g.kO.prototype.load.call(this);this.nh=new g7(this,this.player,this.tb);var a=(a=FJa())?a.currentTime:0;var b=d7()?new y6(Y6(),void 0):null;0==a&&b&&(a=u6(z6(b)));0!==a&&this.xb(a);KJa(this,this.Jc,this.Jc);this.player.Gj(6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.fl=this.fi;g.Zf(this.nh,this.tb);this.tb=this.nh=null;g.kO.prototype.unload.call(this);this.player.Gj(5);p7(this)};
g.k.aa=function(){g.Jo(this.subscriptions);g.kO.prototype.aa.call(this)};
g.k.xj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.nh.KB.apply(this.nh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Ke};
g.k.jL=function(){return this.loaded?this.nh.suggestion:null};
g.k.hj=function(){return this.tb?z6(this.tb).hj:!1};
g.k.hasNext=function(){return this.tb?z6(this.tb).hasNext:!1};
g.k.xb=function(a,b){this.vE=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.vE};
g.k.getProgressState=function(){var a=z6(this.tb),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.P().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ie():!a.isAdPlaying()&&this.player.Ie(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+s6(a):a.B,isAtLiveHead:1>=(a.u?a.l+s6(a):a.l)-this.getCurrentTime(),loaded:a.T,seekableEnd:a.u?a.l+s6(a):a.l,seekableStart:0<a.C?a.C+
s6(a):a.C}};
g.k.nextVideo=function(){this.tb&&this.tb.nextVideo()};
g.k.Mu=function(){this.tb&&this.tb.Mu()};
g.k.cN=function(a){1===a&&(this.qz=this.tb?z6(this.tb):null)};
g.k.JO=function(){var a=d7()?new y6(Y6(),void 0):null;if(a){var b=this.fl;this.loaded&&this.unload();this.tb=a;this.qz=null;b.key!==this.fi.key&&(this.fl=b,this.load())}else g.Yf(this.tb),this.tb=null,this.loaded&&(this.unload(),(a=this.qz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,u6(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.FF=function(){var a=[this.fi],b=a.concat,c=CJa();m6()&&g.Gu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Pl=b.call(a,c);a=Z6()||this.fi;q7(this,a);this.player.ra("onMdxReceiversChange")};
g.k.HO=function(){var a=Z6();q7(this,a)};
g.k.GO=function(){this.fl=Z6()};
g.k.bQ=function(){this.Jr=!0;p7(this);f7=!1;$6&&b7($6,1);$6=null};
g.k.aQ=function(){this.Jr=!1;p7(this);q7(this,this.fi);this.fl=this.fi;f7=!1;$6=null;this.player.playVideo()};
g.k.iM=function(){this.ou=!0;p7(this);g.Fu("yt-remote-manual-pairing-warning-shown",!0,2592E3);f7=!1;$6&&b7($6,1);$6=null};
g.k.De=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Pl;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?o6():q7(this,b)),this.loaded?this.fl:this.fi;case "quickCast":return 2===this.Pl.length&&"cast-selector-receiver"===this.Pl[1].key?(b&&o6(),!0):!1}};
g.k.hA=function(){this.tb.hA()};
g.k.xi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.qO.remote=o7;})(_yt_player);
